/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Dharunika
 */
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
public class Homepage extends javax.swing.JFrame {

    /**
     * Creates new form Homepage
     */
    public Homepage() {
      initComponents();
setTitle("AI Interview Prep Portal");
        setSize(1280, 800);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLayout(new BorderLayout());

        // Create a panel with custom painting for gradient background
        JPanel backgroundPanel = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                Graphics2D g2d = (Graphics2D) g;
                Color color1 = new Color(62, 100, 255); // Blue
                Color color2 = new Color(255, 107, 107); // Pink
                GradientPaint gp = new GradientPaint(0, 0, color1, 0, getHeight(), color2);
                g2d.setPaint(gp);
                g2d.fillRect(0, 0, getWidth(), getHeight());
            }
        };
        backgroundPanel.setLayout(null); // Absolute positioning for labels/buttons
        add(backgroundPanel);

        // Welcome content using JLabel with HTML
        JLabel welcomeLabel = new JLabel();
        welcomeLabel.setHorizontalAlignment(SwingConstants.CENTER);
        welcomeLabel.setVerticalAlignment(SwingConstants.CENTER);
        welcomeLabel.setText("<html>"
                + "<div style='text-align: center; font-family: Arial; padding: 20px;'>"
                + "<h1 style='color:#FFFFFF; font-size:36px;'>Welcome to <span style='color:#FFD700;'>AI Interview Prep Portal</span></h1>"
                + "<p style='font-size:18px; color:#f0f0f0;'>Empowering learners to master technical interviews with smart AI-powered question generation, performance tracking, and personalized feedback.</p>"
                + "<p style='font-size:16px; color:#e0e0e0; margin-top:15px;'>"
                + "Take tests from various <b>Domains</b> and <b>Companies</b>, track your performance, and stay ready to achieve your dream career!"
                + "</p>"
                + "<h3 style='color:#00FFAA; margin-top:25px;'>“Learn. Practice. Improve. Succeed.”</h3>"
                + "</div>"
                + "</html>");
        welcomeLabel.setBounds(140, 100, 1000, 400);
        backgroundPanel.add(welcomeLabel);

        // Skip Intro button
        JButton skipButton = new JButton("Skip Intro →");
        skipButton.setFont(new Font("Arial", Font.BOLD, 18));
        skipButton.setBackground(new Color(255, 215, 0));
        skipButton.setForeground(Color.BLACK);
        skipButton.setFocusPainted(false);
        skipButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        skipButton.setBounds(550, 650, 180, 50);

        // Add subtle shadow effect (border)
        skipButton.setBorder(BorderFactory.createLineBorder(Color.WHITE, 2));

        skipButton.addActionListener(e -> {
            new LoginPage().setVisible(true);
            dispose();
        });

        backgroundPanel.add(skipButton);

        setLocationRelativeTo(null); // Center the frame
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 860, 470));

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        SwingUtilities.invokeLater(() -> new Homepage().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration                   
}
