/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Dharunika
 */
import javax.swing.*;
import java.awt.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

public class FeedbackPage extends javax.swing.JFrame {
private String username;
    private JTextArea taFeedback;
    private JButton btnSubmit;


    /**
     * Creates new form FeedbackPage
     */
    public FeedbackPage(String username) {
       this.username = username;
        setTitle("Submit Feedback");
        setSize(550, 450);
        setLocationRelativeTo(null);
        setResizable(false);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        // ===== Background Panel =====
        JPanel panel = new JPanel();
        panel.setLayout(null);
        panel.setBackground(new Color(255, 245, 238)); // Soft peach
        setContentPane(panel);

        // ===== Heading =====
        JLabel lblHeading = new JLabel("Give Your Feedback, If You Wish!");
        lblHeading.setFont(new Font("Segoe UI", Font.BOLD, 22));
        lblHeading.setForeground(new Color(51, 102, 255)); // Blue color
        lblHeading.setBounds(50, 20, 450, 30);
        panel.add(lblHeading);

        // ===== Instruction =====
        JLabel lblInstruction = new JLabel("We value your thoughts and suggestions.");
        lblInstruction.setFont(new Font("Segoe UI", Font.ITALIC, 16));
        lblInstruction.setForeground(new Color(102, 102, 102));
        lblInstruction.setBounds(50, 60, 450, 25);
        panel.add(lblInstruction);

        // ===== Feedback TextArea =====
        taFeedback = new JTextArea();
        taFeedback.setLineWrap(true);
        taFeedback.setWrapStyleWord(true);
        taFeedback.setFont(new Font("Segoe UI", Font.PLAIN, 16));
        taFeedback.setBorder(BorderFactory.createLineBorder(new Color(51, 102, 255), 2));
        JScrollPane scroll = new JScrollPane(taFeedback);
        scroll.setBounds(50, 100, 450, 200);
        panel.add(scroll);

        // ===== Submit Button =====
        btnSubmit = new JButton("Submit Feedback");
        btnSubmit.setBackground(new Color(51, 102, 255));
        btnSubmit.setForeground(Color.WHITE);
        btnSubmit.setFont(new Font("Segoe UI", Font.BOLD, 16));
        btnSubmit.setBounds(180, 320, 180, 45);
        panel.add(btnSubmit);

        btnSubmit.addActionListener(e -> submitFeedback());

        setVisible(true);
    }
    
    private void submitFeedback() {
        String feedback = taFeedback.getText().trim();
        if (feedback.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your feedback!");
            return;
        }

        try {
            Connection con = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/InterviewQuestion_Generator?useSSL=false&allowPublicKeyRetrieval=true",
                    "root", "Admin#"
            );

            String sql = "INSERT INTO feedbacks(username, feedback_text) VALUES(?, ?)";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, username);
            pst.setString(2, feedback);
            pst.executeUpdate();
            con.close();

            JOptionPane.showMessageDialog(this, "Thank you! Your feedback has been submitted.");
            taFeedback.setText("");

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error saving feedback: " + ex.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FeedbackPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FeedbackPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FeedbackPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FeedbackPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

      new FeedbackPage("testuser").setVisible(true);
    }
    // Variables declaration - do not modify                     
    // End of variables declaration                   
}
