/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Dharunika
 */
import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.sql.*;

public class HistoryPage extends JFrame {
    
    private String username;
    private JTable historyTable;
    
    public HistoryPage(String username) {
         this.username = username;
        setupUI();
        loadHistory();
        setSize(900, 600);
        setLocationRelativeTo(null);
        setResizable(false);
        setVisible(true);
    }
    
   private void setupUI() {
        setTitle("My Test History");
        getContentPane().setLayout(new BorderLayout());

        // Header
        JLabel lblTitle = new JLabel("📜 Test History for " + username, SwingConstants.CENTER);
        lblTitle.setFont(new Font("Segoe UI", Font.BOLD, 26));
        lblTitle.setOpaque(true);
        lblTitle.setBackground(new Color(102, 204, 255));
        lblTitle.setForeground(Color.WHITE);
        lblTitle.setPreferredSize(new Dimension(100, 60));
        getContentPane().add(lblTitle, BorderLayout.NORTH);

        // Table
        String[] columns = {"Test Name", "Type", "Score", "Taken At"};
        historyTable = new JTable(new DefaultTableModel(columns, 0));
        historyTable.setFont(new Font("Segoe UI", Font.PLAIN, 16));
        historyTable.setRowHeight(25);
        historyTable.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 16));
        historyTable.getTableHeader().setBackground(new Color(0, 102, 204));
        historyTable.getTableHeader().setForeground(Color.WHITE);

        JScrollPane scrollPane = new JScrollPane(historyTable);
        scrollPane.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
        getContentPane().add(scrollPane, BorderLayout.CENTER);

        // Footer with Back
        JPanel footer = new JPanel();
        footer.setBackground(new Color(0, 102, 204));
        JButton btnBack = new JButton("Back to Home");
        btnBack.setFont(new Font("Segoe UI", Font.BOLD, 18));
        btnBack.setBackground(Color.WHITE);
        btnBack.setForeground(new Color(0, 102, 204));
        btnBack.setFocusPainted(false);
        btnBack.addActionListener(evt -> {
            dispose();
            new UserHomePage(username).setVisible(true);
        });
        footer.add(btnBack);
        getContentPane().add(footer, BorderLayout.SOUTH);
    }

    private void loadHistory() {
        DefaultTableModel model = (DefaultTableModel) historyTable.getModel();
        model.setRowCount(0);

        try (Connection conn = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/InterviewQuestion_Generator", "root", "Admin#");
             PreparedStatement ps = conn.prepareStatement(
                     "SELECT t.selected, t.type, t.score, t.taken_at " +
                     "FROM tests t JOIN users u ON t.user_id = u.id WHERE u.username = ? ORDER BY t.taken_at DESC")) {

            ps.setString(1, username);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                model.addRow(new Object[]{
                        rs.getString("selected"),
                        rs.getString("type"),
                        rs.getInt("score"),
                        rs.getTimestamp("taken_at")
                });
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading history: " + e.getMessage());
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistoryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistoryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistoryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistoryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               SwingUtilities.invokeLater(() -> new HistoryPage("Dharunika"));            }
        });
    }

    // Variables declaration - do not modify                     
    // End of variables declaration                   
}
