/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Dharunika
 */
import javax.swing.*;
import java.awt.*;
import java.sql.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class ComplaintsPage extends javax.swing.JFrame {
    private String username;
    private JTextArea taComplaint;
    private JButton btnSubmit;
    /**
     * Creates new form ComplaintsPage
     */
    public ComplaintsPage(String username) {
       this.username = username;
        setTitle("Submit Complaint");
        setSize(550, 450);
        setLocationRelativeTo(null);
        setResizable(false);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        // ===== Background Panel =====
        JPanel panel = new JPanel();
        panel.setLayout(null);
        panel.setBackground(new Color(240, 255, 255)); // Light cyan
        setContentPane(panel);

        // ===== Heading =====
        JLabel lblHeading = new JLabel("Your Complaints Can Be Posted Here!");
        lblHeading.setFont(new Font("Segoe UI", Font.BOLD, 22));
        lblHeading.setForeground(new Color(204, 0, 0)); // Dark red
        lblHeading.setBounds(40, 20, 500, 30);
        panel.add(lblHeading);

        // ===== Instruction =====
        JLabel lblInstruction = new JLabel("We assure you that your complaints will be reviewed.");
        lblInstruction.setFont(new Font("Segoe UI", Font.ITALIC, 16));
        lblInstruction.setForeground(new Color(102, 102, 102));
        lblInstruction.setBounds(40, 60, 500, 25);
        panel.add(lblInstruction);

        // ===== Complaint TextArea =====
        taComplaint = new JTextArea();
        taComplaint.setLineWrap(true);
        taComplaint.setWrapStyleWord(true);
        taComplaint.setFont(new Font("Segoe UI", Font.PLAIN, 16));
        taComplaint.setBorder(BorderFactory.createLineBorder(new Color(204, 0, 0), 2));
        JScrollPane scroll = new JScrollPane(taComplaint);
        scroll.setBounds(40, 100, 470, 200);
        panel.add(scroll);

        // ===== Submit Button =====
        btnSubmit = new JButton("Submit Complaint");
        btnSubmit.setBackground(new Color(204, 0, 0));
        btnSubmit.setForeground(Color.WHITE);
        btnSubmit.setFont(new Font("Segoe UI", Font.BOLD, 16));
        btnSubmit.setBounds(180, 320, 200, 45);
        panel.add(btnSubmit);

        btnSubmit.addActionListener(e -> submitComplaint());

        setVisible(true);
    }
    
private void submitComplaint() {
        String complaint = taComplaint.getText().trim();
        if (complaint.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your complaint!");
            return;
        }

        try {
            Connection con = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/InterviewQuestion_Generator?useSSL=false&allowPublicKeyRetrieval=true",
                    "root", "Admin#"
            );

            LocalDateTime now = LocalDateTime.now();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
            String submittedOn = now.format(formatter);

            String sql = "INSERT INTO complaints(username, complaint_text, submitted_on) VALUES(?, ?, ?)";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, username);
            pst.setString(2, complaint);
            pst.setString(3, submittedOn);
            pst.executeUpdate();
            con.close();

            JOptionPane.showMessageDialog(this, "Your complaint has been submitted successfully!");
            taComplaint.setText("");

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error saving complaint: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComplaintsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComplaintsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComplaintsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComplaintsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       new ComplaintsPage("testuser").setVisible(true);
    }
          

    // Variables declaration - do not modify                     
    // End of variables declaration                   
}
